######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "C:/Xilinx/Projects/zed_first/zed_first.srcs/sources_1/edk/proc_module"
  if { [ catch {xload xmp proc_module.xmp} result ] } {
    exit 10
  }
  run drc
  return $result
}

# Run DRC
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
